/* Modernizr 2.8.3 (Custom Build) | MIT & BSD
 * Build: http://modernizr.com/download/#-borderimage-flexbox-hsla-multiplebgs-opacity-rgba-cssanimations-csscolumns-generatedcontent-cssreflections-csstransforms-csstransforms3d-csstransitions-canvas-canvastext-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-geolocation-inlinesvg-smil-svg-svgclippaths-touch-webgl-shiv-cssclasses-addtest-prefixed-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes-load
 */window.Modernizr=function(m,e,z){function t(a,b){return typeof a===b}function B(a,b){for(var c in a){var h=a[c];if(!~(""+h).indexOf("-")&&q[h]!==z)return"pfx"==b?h:!0}return!1}function r(a,b,c){var h=a.charAt(0).toUpperCase()+a.slice(1),e=(a+" "+H.join(h+" ")+h).split(" ");if(t(b,"string")||t(b,"undefined"))return B(e,b);e=(a+" "+C.join(h+" ")+h).split(" ");a:{a=e;for(var d in a)if(h=b[a[d]],h!==z){b=!1===c?a[d]:t(h,"function")?h.bind(c||b):h;break a}b=!1}return b}function N(){k.input=function(a){for(var b=
    0,c=a.length;b<c;b++)D[a[b]]=!!(a[b]in g);D.list&&(D.list=!(!e.createElement("datalist")||!m.HTMLDataListElement));return D}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));k.inputtypes=function(a){for(var b=0,c,h,d=a.length;b<d;b++){g.setAttribute("type",h=a[b]);if(c="text"!==g.type)g.value=":)",g.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(h)&&g.style.WebkitAppearance!==z?(v.appendChild(g),c=e.defaultView,c=c.getComputedStyle&&
"textfield"!==c.getComputedStyle(g,null).WebkitAppearance&&0!==g.offsetHeight,v.removeChild(g)):/^(search|tel)$/.test(h)||(c=/^(url|email)$/.test(h)?g.checkValidity&&!1===g.checkValidity():":)"!=g.value);E[a[b]]=!!c}return E}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var k={},v=e.documentElement,d=e.createElement("modernizr"),q=d.style,g=e.createElement("input"),A={}.toString,w=" -webkit- -moz- -o- -ms- ".split(" "),H=["Webkit","Moz","O","ms"],
    C=["webkit","moz","o","ms"],d={},E={},D={},I=[],J=I.slice,F,K=function(a,b,c,h){var d,k,x=e.createElement("div"),n=e.body,f=n||e.createElement("body");if(parseInt(c,10))for(;c--;)d=e.createElement("div"),d.id=h?h[c]:"modernizr"+(c+1),x.appendChild(d);c=['&#173;<style id="smodernizr">',a,"</style>"].join("");x.id="modernizr";(n?x:f).innerHTML+=c;f.appendChild(x);n||(f.style.background="",f.style.overflow="hidden",k=v.style.overflow,v.style.overflow="hidden",v.appendChild(f));a=b(x,a);n?x.parentNode.removeChild(x):
        (f.parentNode.removeChild(f),v.style.overflow=k);return!!a},M=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||e.createElement(a[b]||"div");b="on"+b;var h=b in c;h||(c.setAttribute||(c=e.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),h=t(c[b],"function"),t(c[b],"undefined")||(c[b]=z),c.removeAttribute(b)));return h}}(),G={}.hasOwnProperty,u;u=t(G,"undefined")||t(G.call,"undefined")?
    function(a,b){return b in a&&t(a.constructor.prototype[b],"undefined")}:function(a,b){return G.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=J.call(arguments,1),h=function(){if(this instanceof h){var d=function(){};d.prototype=b.prototype;var d=new d,e=b.apply(d,c.concat(J.call(arguments)));return Object(e)===e?e:d}return b.apply(a,c.concat(J.call(arguments)))};return h});d.flexbox=function(){return r("flexWrap")};
    d.canvas=function(){var a=e.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};d.canvastext=function(){return!(!k.canvas||!t(e.createElement("canvas").getContext("2d").fillText,"function"))};d.webgl=function(){return!!m.WebGLRenderingContext};d.touch=function(){var a;"ontouchstart"in m||m.DocumentTouch&&e instanceof DocumentTouch?a=!0:K(["@media (",w.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop});return a};d.geolocation=
        function(){return"geolocation"in navigator};d.postmessage=function(){return!!m.postMessage};d.indexedDB=function(){return!!r("indexedDB",m)};d.hashchange=function(){return M("hashchange",m)&&(e.documentMode===z||7<e.documentMode)};d.history=function(){return!(!m.history||!history.pushState)};d.rgba=function(){q.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+q.backgroundColor).indexOf("rgba")};d.hsla=function(){q.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+q.backgroundColor).indexOf("rgba")||
        !!~(""+q.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){q.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(q.background)};d.borderimage=function(){return r("borderImage")};d.opacity=function(){var a=w.join("opacity:.55;")+"";q.cssText=a;return/^0.55$/.test(q.opacity)};d.cssanimations=function(){return r("animationName")};d.csscolumns=function(){return r("columnCount")};d.cssreflections=function(){return r("boxReflect")};d.csstransforms=function(){return!!r("transform")};
    d.csstransforms3d=function(){var a=!!r("perspective");a&&"webkitPerspective"in v.style&&K("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,c){a=9===b.offsetLeft&&3===b.offsetHeight});return a};d.csstransitions=function(){return r("transition")};d.generatedcontent=function(){var a;K('#modernizr{font:0/0 a}#modernizr:after{content:":)";visibility:hidden;font:3px/1 a}',function(b){a=3<=b.offsetHeight});return a};d.video=function(){var a=e.createElement("video"),
        b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};d.audio=function(){var a=e.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,
        ""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};d.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};d.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};d.svg=function(){return!!e.createElementNS&&
        !!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};d.inlinesvg=function(){var a=e.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};d.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(A.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};d.svgclippaths=function(){return!!e.createElementNS&&/SVGClipPath/.test(A.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var L in d)u(d,
        L)&&(F=L.toLowerCase(),k[F]=d[L](),I.push((k[F]?"":"no-")+F));k.input||N();k.addTest=function(a,b){if("object"==typeof a)for(var c in a)u(a,c)&&k.addTest(c,a[c]);else{a=a.toLowerCase();if(k[a]!==z)return k;b="function"==typeof b?b():b;v.className+=" "+(b?"":"no-")+a;k[a]=b}return k};q.cssText="";d=g=null;(function(a,b){function c(){var c=l.elements;return"string"==typeof c?c.split(" "):c}function h(c){var b=r[c._html5shiv];b||(b={},g++,c._html5shiv=g,r[g]=b);return b}function d(c,a,e){a||(a=b);if(y)return a.createElement(c);
        e||(e=h(a));a=e.cache[c]?e.cache[c].cloneNode():O.test(c)?(e.cache[c]=e.createElem(c)).cloneNode():e.createElem(c);return!a.canHaveChildren||f.test(c)||a.tagUrn?a:e.frag.appendChild(a)}function e(b,a){a.cache||(a.cache={},a.createElem=b.createElement,a.createFrag=b.createDocumentFragment,a.frag=a.createFrag());b.createElement=function(c){return l.shivMethods?d(c,b,a):a.createElem(c)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+
    c().join().replace(/[\w\-]+/g,function(c){a.createElem(c);a.frag.createElement(c);return'c("'+c+'")'})+");return n}")(l,a.frag)}function k(c){c||(c=b);var a=h(c);if(l.shivCSS&&!p&&!a.hasCSS){var d,f=c;d=f.createElement("p");f=f.getElementsByTagName("head")[0]||f.documentElement;d.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>";d=f.insertBefore(d.lastChild,f.firstChild);a.hasCSS=
        !!d}y||e(c,a);return c}var n=a.html5||{},f=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,O=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,p,g=0,r={},y;(function(){try{var c=b.createElement("a");c.innerHTML="<xyz></xyz>";p="hidden"in c;var a;if(!(a=1==c.childNodes.length)){b.createElement("a");var h=b.createDocumentFragment();a="undefined"==typeof h.cloneNode||"undefined"==typeof h.createDocumentFragment||"undefined"==
    typeof h.createElement}y=a}catch(d){y=p=!0}})();var l={elements:n.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==n.shivCSS,supportsUnknownElements:y,shivMethods:!1!==n.shivMethods,type:"default",shivDocument:k,createElement:d,createDocumentFragment:function(a,d){a||(a=b);if(y)return a.createDocumentFragment();d=d||h(a);for(var e=
        d.frag.cloneNode(),l=0,f=c(),p=f.length;l<p;l++)e.createElement(f[l]);return e}};a.html5=l;k(b)})(this,e);k._version="2.8.3";k._prefixes=w;k._domPrefixes=C;k._cssomPrefixes=H;k.hasEvent=M;k.testProp=function(a){return B([a])};k.testAllProps=r;k.testStyles=K;k.prefixed=function(a,b,c){return b?r(a,b,c):r(a,"pfx")};v.className=v.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+I.join(" "));return k}(this,this.document);
(function(m,e,z){function t(c){return"[object Function]"==H.call(c)}function B(c){return"string"==typeof c}function r(){}function N(c){return!c||"loaded"==c||"complete"==c||"uninitialized"==c}function k(){var c=C.shift();E=1;c?c.t?A(function(){("c"==c.t?b.injectCss:b.injectJs)(c.s,0,c.a,c.x,c.e,1)},0):(c(),k()):E=0}function v(c,a,d,g,x,n,f){function O(b){if(!r&&N(p.readyState)&&(y.r=r=1,!E&&k(),p.onload=p.onreadystatechange=null,b)){"img"!=c&&A(function(){J.removeChild(p)},50);for(var d in u[a])u[a].hasOwnProperty(d)&&
u[a][d].onload()}}f=f||b.errorTimeout;var p=e.createElement(c),r=0,m=0,y={t:d,s:a,e:x,a:n,x:f};1===u[a]&&(m=1,u[a]=[]);"object"==c?p.data=a:(p.src=a,p.type=c);p.width=p.height="0";p.onerror=p.onload=p.onreadystatechange=function(){O.call(this,m)};C.splice(g,0,y);"img"!=c&&(m||2===u[a]?(J.insertBefore(p,I?null:w),A(O,f)):u[a].push(p))}function d(a,b,d,e,g){return E=0,b=b||"j",B(a)?v("c"==b?K:F,a,b,this.i++,d,e,g):(C.splice(this.i++,0,a),1==C.length&&k()),this}function q(){var a=b;return a.loader={load:d,
    i:0},a}var g=e.documentElement,A=m.setTimeout,w=e.getElementsByTagName("script")[0],H={}.toString,C=[],E=0,D="MozAppearance"in g.style,I=D&&!!e.createRange().compareNode,J=I?g:w.parentNode,g=m.opera&&"[object Opera]"==H.call(m.opera),g=!!e.attachEvent&&!g,F=D?"object":g?"script":"img",K=g?"script":F,M=Array.isArray||function(a){return"[object Array]"==H.call(a)},G=[],u={},L={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},a,b;b=function(a){function d(a){a=a.split("!");var b=G.length,c=
    a.pop(),e=a.length,c={url:c,origUrl:c,prefixes:a},h,l,f;for(l=0;l<e;l++)f=a[l].split("="),(h=L[f.shift()])&&(c=h(c,f));for(l=0;l<b;l++)c=G[l](c);return c}function e(a,c,b,f,k){var l=d(a),g=l.autoCallback;l.url.split(".").pop().split("?").shift();l.bypass||(c&&(c=t(c)?c:c[a]||c[f]||c[a.split("/").pop().split("?")[0]]),l.instead?l.instead(a,c,b,f,k):(u[l.url]?l.noexec=!0:u[l.url]=1,b.load(l.url,l.forceCSS||!l.forceJS&&"css"==l.url.split(".").pop().split("?").shift()?"c":z,l.noexec,l.attrs,l.timeout),
(t(c)||t(g))&&b.load(function(){q();c&&c(l.origUrl,k,f);g&&g(l.origUrl,k,f);u[l.url]=2})))}function k(a,c){function b(a,f){if(a)if(B(a))f||(h=function(){var a=[].slice.call(arguments);g.apply(this,a);n()}),e(a,h,c,0,d);else{if(Object(a)===a)for(q in m=function(){var c=0,b;for(b in a)a.hasOwnProperty(b)&&c++;return c}(),a)a.hasOwnProperty(q)&&(!f&&!--m&&(t(h)?h=function(){var a=[].slice.call(arguments);g.apply(this,a);n()}:h[q]=function(a){return function(){var c=[].slice.call(arguments);a&&a.apply(this,
    c);n()}}(g[q])),e(a[q],h,c,q,d))}else!f&&n()}var d=!!a.test,f=a.load||a.both,h=a.callback||r,g=h,n=a.complete||r,m,q;b(d?a.yep:a.nope,!!f);f&&b(f)}var g,n,f=this.yepnope.loader;if(B(a))e(a,0,f,0);else if(M(a))for(g=0;g<a.length;g++)n=a[g],B(n)?e(n,0,f,0):M(n)?b(n):Object(n)===n&&k(n,f);else Object(a)===a&&k(a,f)};b.addPrefix=function(a,b){L[a]=b};b.addFilter=function(a){G.push(a)};b.errorTimeout=1E4;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
    a=function(){e.removeEventListener("DOMContentLoaded",a,0);e.readyState="complete"},0));m.yepnope=q();m.yepnope.executeStack=k;m.yepnope.injectJs=function(a,d,g,m,q,n){var f=e.createElement("script"),t,p;m=m||b.errorTimeout;f.src=a;for(p in g)f.setAttribute(p,g[p]);d=n?k:d||r;f.onreadystatechange=f.onload=function(){!t&&N(f.readyState)&&(t=1,d(),f.onload=f.onreadystatechange=null)};A(function(){t||(t=1,d(1))},m);q?f.onload():w.parentNode.insertBefore(f,w)};m.yepnope.injectCss=function(a,b,d,g,m,n){g=
    e.createElement("link");var f;b=n?k:b||r;g.href=a;g.rel="stylesheet";g.type="text/css";for(f in d)g.setAttribute(f,d[f]);m||(w.parentNode.insertBefore(g,w),A(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};